### ISSUE TITLE
老哥我想改坐标但是需要他截屏一直报错

### ISSUE THREAD

**Issue by 4499dsq** [jxwnzzq/DDZJPQ#1]
小白求问，我的分辨率与你的不同，坐标也不一样。我哪怕改了坐标也不能使他正常截屏，或者记录。可以求问一下嘛？我的Py是3.9版本的。软件可以正常启动，但是无法记录
Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\python\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\AI\DDZJPQ-main\GUI_1.0.py", line 473, in GetCard
    img = Image.open("./ScreenPic/M175052.png")
  File "E:\python学习\PycharmProjects\xue\venv\lib\site-packages\PIL\Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './ScreenPic/M175052.png'

**Comment by jxwnzzq** [comment]
截屏只是用来方便制作牌点模板，手工截图也可以的。
你把被注释的截屏部分代码放开，把读文件那行注释掉试试


***@***.***
 
发件人： 4499dsq
发送时间： 2023-08-25 20:14
收件人： jxwnzzq/DDZJPQ
抄送： Subscribed
主题： [jxwnzzq/DDZJPQ] 老哥我想改坐标但是需要他截屏一直报错 (Issue #1)
小白求问，我的分辨率与你的不同，坐标也不一样。我哪怕改了坐标也不能使他正常截屏，或者记录。可以求问一下嘛？我的Py是3.9版本的。软件可以正常启动，但是无法记录
Exception in Tkinter callback
Traceback (most recent call last):
File "E:\python\lib\tkinter_init_.py", line 1892, in call
return self.func(*args)
File "D:\AI\DDZJPQ-main\GUI_1.0.py", line 473, in GetCard
img = Image.open("./ScreenPic/M175052.png")
File "E:\python学习\PycharmProjects\xue\venv\lib\site-packages\PIL\Image.py", line 3218, in open
fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './ScreenPic/M175052.png'
